### ISSUE TITLE
Invalid unicode characters

### ISSUE THREAD

**Issue by huberemanuel** [UniversalDependencies/UD_Portuguese-PetroGold#2]
Hi, some sentences contains invalid unicodes characters, such as `279-20140530-MONOGRAFIA_0-208` on token 5 with:
```
5			NOUN	_	Gender=Masc|Number=Sing	8	nsubj	_	_
```

**Comment by alvelvis** [comment]
Hi @huberemanuel , thanks for noticing.
We had several issues converting the original pdf files to the current conll-u ones and several sentences had to be discarded due to these issues, some others we opted to keep in the corpus since such characters would not make it difficult to understand the sentence.

But I see some of these characters still have wrong annotation (this one that you used as example is probably not a NOUN subject), have you found any automatic way to detect these?

**Comment by huberemanuel** [comment]
Sure, I used the following code to find some errors. I'm not sure if it captures all of them.

```
from conllu import parse

sents = parse(open("../data/UD_Portuguese-PetroGold/pt_petrogold-ud-test.conllu", encoding="utf-8", errors="replace").read())

for sent in sents:
    for i, token in enumerate(sent):
        if isinstance(token["id"], int):
            if token["form"] in ["", ""]:
                print("{} - {} - {} - {}".format(sent.metadata["sent_id"], i, token["form"], token["upos"]))
```

Update:
Found these in the training file:
`["", "", "" "", "", "", "", "", "", "", "", "", "", "", "", "–"]`

**Comment by alvelvis** [comment]
I fixed the annotation of non-unicode characters, thanks for the list of forms.

BTW, if you want to query the whole treebank and not just the training partition you can use `not-to-release/petrogold.conllu` in `dev` branch
